export const citiesByState = {
  Alabama: [
    "Birmingham",
    "Huntsville",
    "Montgomery",
    "Mobile",
    "Tuscaloosa",
    "Hoover",
    "Dothan",
    "Auburn",
    "Decatur",
    "Madison",
    "Florence",
    "Gadsden",
  ],
  Alaska: [
    "Anchorage",
    "Fairbanks",
    "Juneau",
    "Sitka",
    "Ketchikan",
    "Wasilla",
    "Kenai",
    "Kodiak",
    "Bethel",
    "Palmer",
    "Homer",
    "Soldotna",
  ],
  Arizona: [
    "Phoenix",
    "Tucson",
    "Mesa",
    "Chandler",
    "Scottsdale",
    "Gilbert",
    "Tempe",
    "Peoria",
    "Surprise",
    "Flagstaff",
    "Yuma",
    "Prescott",
  ],
  Arkansas: [
    "Little Rock",
    "Fort Smith",
    "Fayetteville",
    "Springdale",
    "Jonesboro",
    "North Little Rock",
    "Conway",
    "Rogers",
    "Bentonville",
    "Hot Springs",
    "Pine Bluff",
    "Benton",
  ],
  California: [
    "Los Angeles",
    "San Diego",
    "San Jose",
    "San Francisco",
    "Fresno",
    "Sacramento",
    "Long Beach",
    "Oakland",
    "Bakersfield",
    "Anaheim",
    "Santa Ana",
    "Riverside",
    "Stockton",
    "Chula Vista",
    "Irvine",
    "Fremont",
    "San Bernardino",
    "Modesto",
  ],
  Colorado: [
    "Denver",
    "Colorado Springs",
    "Aurora",
    "Fort Collins",
    "Lakewood",
    "Thornton",
    "Arvada",
    "Westminster",
    "Pueblo",
    "Centennial",
    "Boulder",
    "Greeley",
  ],
  Connecticut: [
    "Bridgeport",
    "New Haven",
    "Stamford",
    "Hartford",
    "Waterbury",
    "Norwalk",
    "Danbury",
    "New Britain",
    "Meriden",
    "Bristol",
    "West Haven",
    "Milford",
  ],
  Delaware: [
    "Wilmington",
    "Dover",
    "Newark",
    "Middletown",
    "Smyrna",
    "Seaford",
    "Georgetown",
    "Elsmere",
    "New Castle",
    "Milford",
    "Laurel",
    "Harrington",
  ],
  Florida: [
    "Jacksonville",
    "Miami",
    "Tampa",
    "Orlando",
    "St. Petersburg",
    "Hialeah",
    "Tallahassee",
    "Fort Lauderdale",
    "Port St. Lucie",
    "Cape Coral",
    "Pembroke Pines",
    "Hollywood",
    "Miramar",
    "Gainesville",
    "Coral Springs",
    "Miami Gardens",
    "Clearwater",
    "Palm Bay",
  ],
  Georgia: [
    "Atlanta",
    "Augusta",
    "Columbus",
    "Macon",
    "Savannah",
    "Athens",
    "Sandy Springs",
    "Roswell",
    "Albany",
    "Johns Creek",
    "Warner Robins",
    "Valdosta",
  ],
  Hawaii: [
    "Honolulu",
    "Pearl City",
    "Hilo",
    "Kailua",
    "Waipahu",
    "Kaneohe",
    "Mililani",
  ],
  Idaho: [
    "Boise",
    "Nampa",
    "Meridian",
    "Idaho Falls",
    "Pocatello",
    "Caldwell",
    "Coeur d'Alene",
    "Twin Falls",
    "Lewiston",
    "Rexburg",
    "Eagle",
    "Moscow",
  ],
  Illinois: [
    "Chicago",
    "Aurora",
    "Rockford",
    "Joliet",
    "Naperville",
    "Springfield",
    "Peoria",
    "Elgin",
    "Waukegan",
    "Cicero",
    "Champaign",
    "Bloomington",
  ],
  Indiana: [
    "Indianapolis",
    "Fort Wayne",
    "Evansville",
    "South Bend",
    "Carmel",
    "Fishers",
    "Bloomington",
    "Hammond",
    "Gary",
    "Muncie",
    "Anderson",
    "Terre Haute",
  ],
  Iowa: [
    "Des Moines",
    "Cedar Rapids",
    "Davenport",
    "Sioux City",
    "Iowa City",
    "Waterloo",
    "Council Bluffs",
    "Dubuque",
    "Ames",
    "Ankeny",
    "Urbandale",
    "Cedar Falls",
  ],
  Kansas: [
    "Wichita",
    "Overland Park",
    "Kansas City",
    "Topeka",
    "Olathe",
    "Lawrence",
    "Shawnee",
    "Manhattan",
    "Lenexa",
    "Salina",
    "Hutchinson",
    "Leavenworth",
  ],
  Kentucky: [
    "Louisville",
    "Lexington",
    "Bowling Green",
    "Owensboro",
    "Covington",
    "Richmond",
    "Hopkinsville",
    "Florence",
    "Georgetown",
    "Elizabethtown",
    "Nicholasville",
    "Henderson",
  ],

  Louisiana: [
    "New Orleans",
    "Baton Rouge",
    "Shreveport",
    "Lafayette",
    "Lake Charles",
    "Kenner",
    "Bossier City",
    "Monroe",
    "Alexandria",
    "Houma",
    "Minden",
    "Mandeville",
  ],
  Maine: [
    "Portland",
    "Lewiston",
    "Bangor",
    "South Portland",
    "Auburn",
    "Biddeford",
    "Augusta",
    "Saco",
    "Westbrook",
    "Waterville",
    "Brunswick",
    "Scarborough",
  ],
  Maryland: [
    "Annapolis",
    "Baltimore",
    "Frederick",
    "Gaithersburg",
    "Hagerstown",
    "Rockville",
    "Salisbury",
    "Westminster",
  ],
  Massachusetts: [
    "Boston",
    "Brockton",
    "Cambridge",
    "Fall River",
    "Lowell",
    "Lynn",
    "New Bedford",
    "Quincy",
    "Springfield",
    "Worcester",
  ],
  Michigan: [
    "Ann Arbor",
    "Detroit",
    "Flint",
    "Grand Rapids",
    "Kalamazoo",
    "Lansing",
    "Muskegon",
    "Saginaw",
    "Traverse City",
  ],
  Minnesota: [
    "Duluth",
    "Mankato",
    "Minneapolis",
    "Moorhead",
    "Rochester",
    "Saint Cloud",
    "Saint Paul",
    "Winona",
  ],
  Mississippi: [
    "Biloxi",
    "Greenville",
    "Gulfport",
    "Hattiesburg",
    "Jackson",
    "Meridian",
    "Oxford",
    "Tupelo",
    "Vicksburg",
  ],
  Missouri: [
    "Columbia",
    "Independence",
    "Jefferson City",
    "Joplin",
    "Kansas City",
    "Saint Charles",
    "Saint Joseph",
    "Saint Louis",
    "Springfield",
  ],
  Montana: [
    "Billings",
    "Bozeman",
    "Butte",
    "Great Falls",
    "Helena",
    "Kalispell",
    "Missoula",
  ],
  Nebraska: [
    "Bellevue",
    "Fremont",
    "Grand Island",
    "Kearney",
    "Lincoln",
    "Norfolk",
    "North Platte",
    "Omaha",
    "Scottsbluff",
  ],
  Nevada: [
    "Boulder City",
    "Carson City",
    "Elko",
    "Henderson",
    "Las Vegas",
    "Mesquite",
    "North Las Vegas",
    "Reno",
    "Sparks",
  ],
  "New Hampshire": [
    "Concord",
    "Dover",
    "Keene",
    "Laconia",
    "Manchester",
    "Nashua",
    "Portsmouth",
    "Rochester",
  ],
  "New Jersey": [
    "Atlantic City",
    "Camden",
    "Clifton",
    "Elizabeth",
    "Hoboken",
    "Jersey City",
    "Newark",
    "Passaic",
    "Paterson",
    "Trenton",
  ],
  "New Mexico": [
    "Alamogordo",
    "Albuquerque",
    "Carlsbad",
    "Clovis",
    "Farmington",
    "Gallup",
    "Las Cruces",
    "Roswell",
    "Santa Fe",
  ],
  "New York": [
    "Albany",
    "Binghamton",
    "Buffalo",
    "Elmira",
    "Ithaca",
    "Kingston",
    "New Rochelle",
    "New York City",
    "Poughkeepsie",
    "Rochester",
    "Syracuse",
    "Troy",
    "Utica",
    "White Plains",
    "Yonkers",
  ],
  "North Carolina": [
    "Asheville",
    "Chapel Hill",
    "Charlotte",
    "Durham",
    "Fayetteville",
    "Greensboro",
    "Greenville",
    "Raleigh",
    "Wilmington",
    "Winston-Salem",
  ],
  "North Dakota": ["Bismarck", "Fargo", "Grand Forks", "Minot"],
  Ohio: [
    "Akron",
    "Cincinnati",
    "Cleveland",
    "Columbus",
    "Dayton",
    "Lima",
    "Mansfield",
    "Toledo",
    "Youngstown",
  ],
  Oklahoma: [
    "Bartlesville",
    "Enid",
    "Lawton",
    "Muskogee",
    "Norman",
    "Oklahoma City",
    "Shawnee",
    "Tulsa",
  ],
  Oregon: ["Bend", "Corvallis", "Eugene", "Medford", "Portland", "Salem"],
  Pennsylvania: [
    "Allentown",
    "Altoona",
    "Bethlehem",
    "Erie",
    "Harrisburg",
    "Lancaster",
    "Philadelphia",
    "Pittsburgh",
    "Reading",
    "Scranton",
    "State College",
    "Wilkes-Barre",
    "York",
  ],
  "Rhode Island": ["Cranston", "Newport", "Pawtucket", "Providence", "Warwick"],
  "South Carolina": [
    "Charleston",
    "Columbia",
    "Florence",
    "Greenville",
    "Myrtle Beach",
    "Rock Hill",
    "Spartanburg",
  ],
  "South Dakota": [
    "Sioux Falls",
    "Rapid City",
    "Aberdeen",
    "Brookings",
    "Watertown",
    "Mitchell",
  ],
  Tennessee: [
    "Nashville",
    "Memphis",
    "Knoxville",
    "Chattanooga",
    "Clarksville",
    "Murfreesboro",
  ],
  Texas: [
    "Houston",
    "San Antonio",
    "Dallas",
    "Austin",
    "Fort Worth",
    "El Paso",
    "Arlington",
    "Corpus Christi",
    "Plano",
    "Laredo",
    "Garland",
    "Irving",
    "Frisco",
    "McKinney",
    "Pasadena",
    "Mesquite",
    "Killeen",
    "Waco",
    "Denton",
  ],
  Utah: [
    "Salt Lake City",
    "Provo",
    "Orem",
    "St. George",
    "West Jordan",
    "West Valley City",
  ],
  Vermont: [
    "Burlington",
    "South Burlington",
    "Rutland",
    "Essex",
    "Barre",
    "Montpelier",
  ],
  Virginia: [
    "Virginia Beach",
    "Norfolk",
    "Chesapeake",
    "Richmond",
    "Newport News",
    "Alexandria",
  ],
  Washington: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent"],
  "West Virginia": [
    "Charleston",
    "Huntington",
    "Morgantown",
    "Parkersburg",
    "Wheeling",
    "Clarksburg",
  ],
  Wisconsin: [
    "Milwaukee",
    "Madison",
    "Green Bay",
    "Kenosha",
    "Racine",
    "Appleton",
  ],
  Wyoming: [
    "Cheyenne",
    "Casper",
    "Laramie",
    "Gillette",
    "Rock Springs",
    "Sheridan",
  ],
};

export function getRandomCityByState() {
  const states = Object.keys(citiesByState);
  const randomState = states[Math.floor(Math.random() * states.length)];
  const cities = citiesByState[randomState];
  const randomCity = cities[Math.floor(Math.random() * cities.length)];
  return `${randomCity}, ${randomState}`;
}

export function generateTeam() {
  const league = {};
  for (const state in citiesByState) {
    league[state] = [];
    const cities = citiesByState[state];
    for (const city of cities) {
      const teamName = `The ${city} ${generateFootballTeamName()}`;
      league[state].push(teamName);

      // TODO: create a team with the name `teamName` here
    }
  }
  console.log(league);
}

export function generateFootballTeamName() {
  const adjectives = [
    "Aggressive",
    "Ambitious",
    "Athletic",
    "Bold",
    "Brave",
    "Clever",
    "Confident",
    "Creative",
    "Daring",
    "Determined",
    "Dynamic",
    "Energetic",
    "Fearless",
    "Fierce",
    "Focused",
    "Gritty",
    "Hardworking",
    "Honest",
    "Innovative",
    "Intense",
    "Loyal",
    "Passionate",
    "Powerful",
    "Relentless",
    "Resilient",
    "Resourceful",
    "Smart",
    "Strong",
    "Tough",
    "Unstoppable",
    "Zealous",
    "Adventurous",
    "Assertive",
    "Charismatic",
    "Courageous",
    "Decisive",
    "Devoted",
    "Dominant",
    "Driven",
    "Fearless",
    "Focused",
    "Independent",
    "Inspirational",
    "Leader",
    "Motivated",
    "Persistent",
    "Proud",
    "Quick",
    "Reliable",
    "Skilled",
    "Talented",
    "Tenacious",
    "Undaunted",
    "Vigilant",
    "Visionary",
    "Wise",
    "Versatile",
    "Influential",
    "Courageous",
    "Responsible",
    "Humorous",
    "Patient",
    "Persevering",
    "Outgoing",
    "Efficient",
    "Organized",
    "Creative",
    "Intelligent",
    "Enthusiastic",
    "Charming",
    "Friendly",
    "Outspoken",
    "Innovative",
    "Imaginative",
    "Eloquent",
    "Original",
    "Confident",
    "Optimistic",
    "Passionate",
    "Meticulous",
    "Precise",
    "Professional",
    "Proactive",
    "Resourceful",
    "Strategic",
    "Tactical",
    "Synergistic",
    "Team Player",
    "Collaborative",
    "Committed",
    "Flexible",
    "Persistent",
    "Innovative",
    "Empathetic",
    "Diligent",
    "Curious",
    "Analytical",
  ];
  const nouns = [
    "Spartans",
    "Gladiators",
    "Pioneers",
    "Cavaliers",
    "Crusaders",
    "Vikings",
    "Raiders",
    "Conquerors",
    "Raptors",
    "Cobras",
    "Hurricanes",
    "Dragons",
    "Phoenix",
    "Storm",
    "Thunder",
    "Lightning",
    "Blaze",
    "Heat",
    "Tornadoes",
    "Cyclones",
    "Hawks",
    "Eagles",
    "Falcons",
    "Ravens",
    "Galaxy",
    "Supernova",
    "Lizard People",
    "Titans",
    "Spartans",
    "Gladiators",
    "Patriots",
    "Rockets",
    "Comets",
    "Avalanche",
    "Barracudas",
    "Chargers",
    "Comets",
    "Cowboys",
    "Miners",
    "Bullets",
    "Express",
    "Gunslingers",
    "Marauders",
    "Outlaws",
    "Pirates",
    "Revolution",
    "Roughriders",
    "Bandits",
    "Bombers",
    "Explorers",
    "Mountaineers",
    "Stormtroopers",
    "Thunderbolts",
    "Warriors",
    "Assassins",
    "Blackhawks",
    "Centurions",
    "Glaciers",
    "Gladiators",
    "Guerillas",
    "Knights",
    "Mammoths",
    "Ninjas",
    "Pilots",
    "Predators",
    "Rampage",
    "Rhinos",
    "SaberTooths",
    "Stallions",
    "Trojans",
    "Volcanoes",
    "Wizards",
    "Aviators",
    "Bulldogs",
    "Enforcers",
    "Firebirds",
    "Gators",
    "Generals",
    "Juggernauts",
    "Owls",
    "Prowlers",
    "Pythons",
    "Reapers",
    "Rednecks",
    "Sentinels",
    "Snipers",
    "Tigers",
    "Warthogs",
    "Wrecking Crew",
  ];
  const randomAdjectiveIndex = Math.floor(Math.random() * adjectives.length);
  const randomNounIndex = Math.floor(Math.random() * nouns.length);

  return adjectives[randomAdjectiveIndex] + " " + nouns[randomNounIndex];
}
