type HeaderToPropertyMap = {
  Postion: string;
  Name: string;
  Overall: string;
  Age: string;
  Year: string;
  Location: string;
  School: string;
  Speed: string;
  Acceleration: string;
  Strength: string;
  Agility: string;
  Awareness: string;
  Jumping: string;
  Injury: string;
  Stamina: string;
  Toughness: string;
  Carrying: string;
  Trucking: string;
  BCVision: string;
  StiffArm: string;
  SpinMove: string;
  JukeMove: string;
  BreakTackle: string;
  BreakSack: string;
  ChangeOfDirection: string;
  RunBlock: string;
  PassBlock: string;
  ImpactBlocking: string;
  RunBlockPower: string;
  RunBlockFinesse: string;
  PassBlockPower: string;
  PassBlockFinesse: string;
  LeadBlock: string;
  ThrowPower: string;
  ThrowAccuracyShort: string;
  ThrowAccuracyMedium: string;
  ThrowAccuracyDeep: string;
  ThrowontheRun: string;
  PlayAction: string;
  ThrowUnderPressure: string;
  Tackle: string;
  PowerMoves: string;
  FinesseMoves: string;
  BlockShedding: string;
  Pursuit: string;
  PlayRecognition: string;
  ManCoverage: string;
  ZoneCoverage: string;
  HitPower: string;
  Press: string;
  Catching: string;
  SpectacularCatch: string;
  CatchinTraffic: string;
  ShortRouteRunning: string;
  MediumRouteRunning: string;
  DeepRouteRunning: string;
  Release: string;
  RunAfterCatch: string;
  KickPower: string;
  KickAccuracy: string;
  KickReturn: string;
  [key: string]: string; // add an index signature to allow any string as property name
};

export const headerToPropertyMap: HeaderToPropertyMap = {
  Postion: "position",
  Name: "fullName",
  Overall: "overall",
  Age: "age",
  Year: "year",
  Location: "location",
  School: "school",
  Speed: "stats.generalRatings.Speed",
  Acceleration: "stats.generalRatings.Acceleration",
  Strength: "stats.generalRatings.Strength",
  Agility: "stats.generalRatings.Agility",
  Awareness: "stats.generalRatings.Awareness",
  Jumping: "stats.generalRatings.Jumping",
  Injury: "stats.generalRatings.Injury",
  Stamina: "stats.generalRatings.Stamina",
  Toughness: "stats.generalRatings.Toughness",
  Carrying: "stats.ballCarrierRatings.Carrying",
  Trucking: "stats.ballCarrierRatings.Trucking",
  BCVision: "stats.ballCarrierRatings.BCVision",
  StiffArm: "stats.ballCarrierRatings.StiffArm",
  SpinMove: "stats.ballCarrierRatings.SpinMove",
  JukeMove: "stats.ballCarrierRatings.JukeMove",
  BreakTackle: "stats.ballCarrierRatings.BreakTackle",
  BreakSack: "stats.ballCarrierRatings.BreakSack",
  ChangeOfDirection: "stats.ballCarrierRatings.ChangeOfDirection",
  RunBlock: "stats.blockingRatings.RunBlock",
  PassBlock: "stats.blockingRatings.PassBlock",
  ImpactBlocking: "stats.blockingRatings.ImpactBlocking",
  RunBlockPower: "stats.blockingRatings.RunBlockPower",
  RunBlockFinesse: "stats.blockingRatings.RunBlockFinesse",
  PassBlockPower: "stats.blockingRatings.PassBlockPower",
  PassBlockFinesse: "stats.blockingRatings.PassBlockFinesse",
  LeadBlock: "stats.blockingRatings.LeadBlock",
  ThrowPower: "stats.passingRatings.ThrowPower",
  ThrowAccuracyShort: "stats.passingRatings.ThrowAccuracyShort",
  ThrowAccuracyMedium: "stats.passingRatings.ThrowAccuracyMedium",
  ThrowAccuracyDeep: "stats.passingRatings.ThrowAccuracyDeep",
  ThrowontheRun: "stats.passingRatings.ThrowontheRun",
  PlayAction: "stats.passingRatings.PlayAction",
  ThrowUnderPressure: "stats.passingRatings.ThrowUnderPressure",
  Tackle: "stats.defenseRatings.Tackle",
  PowerMoves: "stats.defenseRatings.PowerMoves",
  FinesseMoves: "stats.defenseRatings.FinesseMoves",
  BlockShedding: "stats.defenseRatings.BlockShedding",
  Pursuit: "stats.defenseRatings.Pursuit",
  PlayRecognition: "stats.defenseRatings.PlayRecognition",
  ManCoverage: "stats.defenseRatings.ManCoverage",
  ZoneCoverage: "stats.defenseRatings.ZoneCoverage",
  HitPower: "stats.defenseRatings.HitPower",
  Press: "stats.defenseRatings.Press",
  Catching: "stats.receivingRatings.Catching",
  SpectacularCatch: "stats.receivingRatings.SpectacularCatch",
  CatchinTraffic: "stats.receivingRatings.CatchinTraffic",
  ShortRouteRunning: "player.stats.receivingRatings.ShortRouteRunning",
  MediumRouteRunning: "player.stats.receivingRatings.MediumRouteRunning",
  DeepRouteRunning: "player.stats.receivingRatings.DeepRouteRunning",
  Release: "player.stats.receivingRatings.Release",
  RunAfterCatch: "player.stats.receivingRatings.RunAfterCatch",
  KickPower: "player.stats.kickingRatings.KickPower",
  KickAccuracy: "player.stats.kickingRatings.KickAccuracy",
  KickReturn: "player.stats.kickingRatings.KickReturn",
};
